MODEL:
  META_DIMS: [ 105, ]
  JEPA_ENABLE: True
  JEPA_CONTEXT_TOKENS: 4
  JEPA_IN_DIM: 1664
  JEPA_ADAPTER_HIDDEN: 4096
  JEPA_FUSION_HEADS: 8
  JEPA_FUSION_LAYERS: 1

DATA:
  DATASET: 'mevid'
  TEST_BATCH: 100

SOLVER:
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 300
  EVAL_PERIOD: 2

OUTPUT_DIR: ''
