MODEL:
  META_DIMS: [ 105, ]
  JEPA_ENABLE: True
  JEPA_FUSION_MODE: 'dense_patch'
  JEPA_IN_DIM: 1664
  JEPA_ADAPTER_HIDDEN: 4096
  JEPA_FUSION_HEADS: 8
  JEPA_FUSION_LAYERS: 1
  JEPA_WRITE_IMAGE_CACHE: False

DATA:
  DATASET: 'mevid'
  TEST_BATCH: 16

SOLVER:
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 300
  EVAL_PERIOD: 2

OUTPUT_DIR: ''
